package io.github.aughtone.datetime.format.resources.timezone

import kotlinx.datetime.TimeZone
import kotlinx.datetime.UtcOffset

// Lookup table for time zone IDs to three-letter abbreviations.

object TimeZoneAbbreviationLookup {

    val timeZoneFullNameMap: Map<String, String> = mapOf(
        "ACDT" to "Australian Central Daylight Time",
        "ACST" to "Australian Central Standard Time",
        "ACT" to "ASEAN Common Time",
        "ADT" to "Atlantic Daylight Time",
        "AEDT" to "Australian Eastern Daylight Time",
        "AEST" to "Australian Eastern Standard Time",
        "AFT" to "Afghanistan Time",
        "AKDT" to "Alaska Daylight Time",
        "AKST" to "Alaska Standard Time",
        "AMST" to "Amazon Summer Time",
        "AMT" to "Amazon Time",
        "ART" to "Argentina Time",
        "AST" to "Arabian Standard Time",
        "AWST" to "Australian Western Standard Time",
        "AZOST" to "Azores Summer Time",
        "AZOT" to "Azores Standard Time",
        "AZT" to "Azerbaijan Time",
        "BDT" to "Brunei Darussalam Time",
        "BIOT" to "British Indian Ocean Time",
        "BIT" to "Baker Island Time",
        "BOT" to "Bolivia Time",
        "BRST" to "Brasilia Summer Time",
        "BRT" to "Brasilia Time",
        "BST" to "Bangladesh Standard Time",
        "BTT" to "Bhutan Time",
        "CAT" to "Central Africa Time",
        "CCT" to "Cocos Islands Time",
        "CDT" to "Central Daylight Time",
        "CEST" to "Central European Summer Time",
        "CET" to "Central European Time",
        "CHADT" to "Chatham Daylight Time",
        "CHAST" to "Chatham Standard Time",
        "CHOT" to "Choibalsan Standard Time",
        "CHOST" to "Choibalsan Summer Time",
        "CHUT" to "Chuuk Time",
        "CIST" to "Clipperton Island Standard Time",
        "CIT" to "Central Indonesia Time",
        "CKT" to "Cook Island Time",
        "CLST" to "Chile Summer Time",
        "CLT" to "Chile Standard Time",
        "COST" to "Colombia Summer Time",
        "COT" to "Colombia Time",
        "CST" to "Central Standard Time",
        "CT" to "China time",
        "CVT" to "Cape Verde Time",
        "CWST" to "Central Western Standard Time (Australia)",
        "CXT" to "Christmas Island Time",
        "DAVT" to "Davis Time",
        "DDUT" to "Dumont-d'Urville Time",
        "EASST" to "Easter Island Summer Time",
        "EAST" to "Easter Island Time",
        "EAT" to "East Africa Time",
        "ECT" to "Ecuador Time",
        "EDT" to "Eastern Daylight Time",
        "EEST" to "Eastern European Summer Time",
        "EET" to "Eastern European Time",
        "EGST" to "Eastern Greenland Summer Time",
        "EGT" to "Eastern Greenland Time",
        "EST" to "Eastern Standard Time",
        "FET" to "Further-eastern European Time",
        "FJST" to "Fiji Standard Time",
        "FJT" to "Fiji Time",
        "FKST" to "Falkland Islands Summer Time",
        "FKT" to "Falkland Island Time",
        "FNT" to "Fernando de Noronha Time",
        "GALT" to "Galapagos Time",
        "GAMT" to "Gambier Time",
        "GET" to "Georgia Standard Time",
        "GFT" to "French Guiana Time",
        "GILT" to "Gilbert Island Time",
        "GMT" to "Greenwich Mean Time",
        "GST" to "Gulf Standard Time",
        "GYT" to "Guyana Time",
        "HDT" to "Hawaii-Aleutian Daylight Time",
        "HAEC" to "Heure Avancée d'Europe Centrale",
        "HST" to "Hawaii Standard Time",
        "HKT" to "Hong Kong Time",
        "HOVT" to "Hovd Time",
        "ICT" to "Indochina Time",
        "IDLW" to "International Date Line West time",
        "IOT" to "Indian Ocean Time",
        "IRDT" to "Iran Daylight Time",
        "IRKT" to "Irkutsk Time",
        "IRST" to "Iran Standard Time",
        "IST" to "India Standard Time",
        "JST" to "Japan Standard Time",
        "KALT" to "Kaliningrad Time",
        "KGT" to "Kyrgyzstan Time",
        "KOST" to "Kosrae Time",
        "KRAT" to "Krasnoyarsk Time",
        "KST" to "Korea Standard Time",
        "LHST" to "Lord Howe Standard Time",
        "LINT" to "Line Islands Time",
        "MAGT" to "Magadan Time",
        "MART" to "Marquesas Time",
        "MAWT" to "Mawson Time",
        "MDT" to "Mountain Daylight Time",
        "MHT" to "Marshall Islands Time",
        "MIST" to "Macquarie Island Station Time",
        "MIT" to "Marquesas Islands Time",
        "MMT" to "Myanmar Standard Time",
        "MSD" to "Moscow Daylight Time",
        "MSK" to "Moscow Standard Time",
        "MST" to "Mountain Standard Time",
        "MUT" to "Mauritius Time",
        "MVT" to "Maldives Time",
        "MYT" to "Malaysia Time",
        "NCT" to "New Caledonia Time",
        "NDT" to "Newfoundland Daylight Time",
        "NFT" to "Norfolk Time",
        "NOVST" to "Novosibirsk Summer Time",
        "NOVT" to "Novosibirsk Time",
        "NPT" to "Nepal Time",
        "NST" to "Newfoundland Standard Time",
        "NT" to "Newfoundland Time",
        "NUT" to "Niue Time",
        "NZDT" to "New Zealand Daylight Time",
        "NZST" to "New Zealand Standard Time",
        "OMST" to "Omsk Standard Time",
        "ORAT" to "Oral Time",
        "PDT" to "Pacific Daylight Time",
        "PET" to "Peru Time",
        "PETT" to "Kamchatka Time",
        "PGT" to "Papua New Guinea Time",
        "PHOT" to "Phoenix Island Time",
        "PHT" to "Philippine Time",
        "PKT" to "Pakistan Standard Time",
        "PMDT" to "Saint Pierre and Miquelon Daylight time",
        "PMST" to "Saint Pierre and Miquelon Standard Time",
        "PONT" to "Pohnpei Standard Time",
        "PST" to "Pacific Standard Time",
        "PYST" to "Paraguay Summer Time",
        "PYT" to "Paraguay Time",
        "RET" to "Reunion Time",
        "ROTT" to "Rothera Time",
        "SAKT" to "Sakhalin Island Time",
        "SAMT" to "Samara Time",
        "SAST" to "South Africa Standard Time",
        "SBT" to "Solomon Islands Time",
        "SCT" to "Seychelles Time",
        "SGT" to "Singapore Time",
        "SRET" to "Srednekolymsk Time",
        "SRT" to "Suriname Time",
        "SST" to "Samoa Standard Time",
        "SYOT" to "Syowa Time",
        "TAHT" to "Tahiti Time",
        "THA" to "Thailand Standard Time",
        "TFT" to "French Southern and Antarctic Time",
        "TJT" to "Tajikistan Time",
        "TKT" to "Tokelau Time",
        "TLT" to "Timor Leste Time",
        "TMT" to "Turkmenistan Time",
        "TOT" to "Tonga Time",
        "TRT" to "Turkey Time",
        "TVT" to "Tuvalu Time",
        "ULAT" to "Ulaanbaatar Time",
        "UTC" to "Coordinated Universal Time",
        "UYST" to "Uruguay Summer Time",
        "UYT" to "Uruguay Time",
        "UZT" to "Uzbekistan Time",
        "VET" to "Venezuela Time",
        "VLAT" to "Vladivostok Time",
        "VOLT" to "Volgograd Time",
        "VOST" to "Vostok Time",
        "VUT" to "Vanuatu Time",
        "WAKT" to "Wake Island Time",
        "WAST" to "West Africa Summer Time",
        "WAT" to "West Africa Time",
        "WEST" to "Western European Summer Time",
        "WET" to "Western European Time",
        "WIT" to "Western Indonesia Time",
        "WST" to "Western Standard Time",
        "YAKT" to "Yakutsk Time",
        "YEKT" to "Yekaterinburg Time"
    )

    val timeZoneAbbreviatedMap: Map<String, Map<String, String>> = mapOf(
        "America/Toronto" to mapOf("-05:00" to "EST", "-04:00" to "EDT"),
        "America/New_York" to mapOf("-05:00" to "EST", "-04:00" to "EDT"),
        "America/Chicago" to mapOf("-06:00" to "CST", "-05:00" to "CDT"),
        "America/Denver" to mapOf("-07:00" to "MST", "-06:00" to "MDT"),
        "America/Los_Angeles" to mapOf("-08:00" to "PST", "-07:00" to "PDT"),
        "America/Phoenix" to mapOf("-07:00" to "MST"),
        "America/Anchorage" to mapOf("-09:00" to "AKST", "-08:00" to "AKDT"),
        "Pacific/Honolulu" to mapOf("-10:00" to "HST"),
        "Europe/London" to mapOf("+00:00" to "GMT", "+01:00" to "BST"),
        "Europe/Paris" to mapOf("+01:00" to "CET", "+02:00" to "CEST"),
        "Europe/Berlin" to mapOf("+01:00" to "CET", "+02:00" to "CEST"),
        "Europe/Madrid" to mapOf("+01:00" to "CET", "+02:00" to "CEST"),
        "Europe/Rome" to mapOf("+01:00" to "CET", "+02:00" to "CEST"),
        "Europe/Brussels" to mapOf("+01:00" to "CET", "+02:00" to "CEST"),
        "Europe/Warsaw" to mapOf("+01:00" to "CET", "+02:00" to "CEST"),
        "Europe/Stockholm" to mapOf("+01:00" to "CET", "+02:00" to "CEST"),
        "Europe/Helsinki" to mapOf("+02:00" to "EET", "+03:00" to "EEST"),
        "Europe/Bucharest" to mapOf("+02:00" to "EET", "+03:00" to "EEST"),
        "Europe/Moscow" to mapOf("+03:00" to "MSK"),
        "Europe/Istanbul" to mapOf("+03:00" to "TRT"),
        "Asia/Tokyo" to mapOf("+09:00" to "JST"),
        "Asia/Seoul" to mapOf("+09:00" to "KST"),
        "Asia/Shanghai" to mapOf("+08:00" to "CST"),
        "Asia/Singapore" to mapOf("+08:00" to "SGT"),
        "Asia/Hong_Kong" to mapOf("+08:00" to "HKT"),
        "Asia/Kolkata" to mapOf("+05:30" to "IST"),
        "Asia/Dubai" to mapOf("+04:00" to "GST"),
        "Asia/Tehran" to mapOf("+03:30" to "IRST", "+04:30" to "IRDT"),
        "Asia/Baghdad" to mapOf("+03:00" to "AST"),
        "Asia/Karachi" to mapOf("+05:00" to "PKT"),
        "Asia/Dhaka" to mapOf("+06:00" to "BDT"),
        "Asia/Bangkok" to mapOf("+07:00" to "ICT"),
        "Asia/Jakarta" to mapOf("+07:00" to "WIB"),
        "Asia/Ulaanbaatar" to mapOf("+08:00" to "ULAT"),
        "Asia/Vladivostok" to mapOf("+10:00" to "VLAT"),
        "Asia/Yakutsk" to mapOf("+09:00" to "YAKT"),
        "Asia/Tbilisi" to mapOf("+04:00" to "GET"),
        "Asia/Yerevan" to mapOf("+04:00" to "AMT"),
        "Asia/Novosibirsk" to mapOf("+07:00" to "NOVT"),
        "Asia/Magadan" to mapOf("+11:00" to "MAGT"),
        "Asia/Manila" to mapOf("+08:00" to "PHT"),
        "Asia/Taipei" to mapOf("+08:00" to "CST"),
        "Asia/Kathmandu" to mapOf("+05:45" to "NPT"),
        "Asia/Riyadh" to mapOf("+03:00" to "AST"),
        "Asia/Amman" to mapOf("+02:00" to "EET", "+03:00" to "EEST"),
        "Asia/Damascus" to mapOf("+02:00" to "EET", "+03:00" to "EEST"),
        "Asia/Beirut" to mapOf("+02:00" to "EET", "+03:00" to "EEST"),
        "Asia/Jerusalem" to mapOf("+02:00" to "IST", "+03:00" to "IDT"),
        "Africa/Cairo" to mapOf("+02:00" to "EET"),
        "Africa/Johannesburg" to mapOf("+02:00" to "SAST"),
        "Africa/Nairobi" to mapOf("+03:00" to "EAT"),
        "Africa/Algiers" to mapOf("+01:00" to "CET"),
        "Africa/Casablanca" to mapOf("+00:00" to "WET", "+01:00" to "WEST"),
        "Africa/Lagos" to mapOf("+01:00" to "WAT"),
        "Africa/Windhoek" to mapOf("+02:00" to "WAT"),
        "Africa/Tripoli" to mapOf("+02:00" to "EET"),
        "Australia/Sydney" to mapOf("+10:00" to "AEST", "+11:00" to "AEDT"),
        "Australia/Melbourne" to mapOf("+10:00" to "AEST", "+11:00" to "AEDT"),
        "Australia/Brisbane" to mapOf("+10:00" to "AEST"),
        "Australia/Perth" to mapOf("+08:00" to "AWST"),
        "Australia/Darwin" to mapOf("+09:30" to "ACST"),
        "Australia/Adelaide" to mapOf("+09:30" to "ACST", "+10:30" to "ACDT"),
        "Australia/Hobart" to mapOf("+10:00" to "AEST", "+11:00" to "AEDT"),
        "Australia/Lord_Howe" to mapOf("+10:30" to "LHST", "+11:00" to "LHDT"),
        "Pacific/Auckland" to mapOf("+12:00" to "NZST", "+13:00" to "NZDT"),
        "Pacific/Fiji" to mapOf("+12:00" to "FJT", "+13:00" to "FJDT"),
        "Pacific/Tahiti" to mapOf("-10:00" to "TAHT"),
        "Pacific/Tongatapu" to mapOf("+13:00" to "TOT"),
        "Pacific/Port_Moresby" to mapOf("+10:00" to "PGT"),
        "Pacific/Apia" to mapOf("+13:00" to "WSST", "+14:00" to "WSDT"),
        "Pacific/Pago_Pago" to mapOf("-11:00" to "SST"),
        "Pacific/Guam" to mapOf("+10:00" to "ChST"),
        "Pacific/Honolulu" to mapOf("-10:00" to "HST"),
        "Atlantic/Reykjavik" to mapOf("+00:00" to "GMT"),
        "Atlantic/Azores" to mapOf("-01:00" to "AZOT", "+00:00" to "AZOST"),
        "Atlantic/Cape_Verde" to mapOf("-01:00" to "CVT"),
        "Antarctica/McMurdo" to mapOf("+12:00" to "NZST", "+13:00" to "NZDT"),
        "Antarctica/Palmer" to mapOf("-03:00" to "CLT"),
        "Antarctica/Troll" to mapOf("+00:00" to "UTC")
    )

    fun getTimeZoneVariants(timeZone: TimeZone): Map<String, String>? =
        timeZoneAbbreviatedMap[timeZone.id]

    fun getTimeZoneAbbreviation(timeZone: TimeZone, offset: UtcOffset): String =
        getTimeZoneVariants(timeZone = timeZone)?.get(offset.toString()) ?: offset.toString()

    fun getTimeZoneFullName(timeZone: TimeZone, offset: UtcOffset): String =
        timeZoneFullNameMap[getTimeZoneAbbreviation(timeZone = timeZone, offset = offset)]
            ?: offset.toString()
}
